name: lint-bash

on:
  push:
    branches:
      - main
    paths:
      - "**.sh"
  pull_request:
    branches:
      - main
    paths:
      - "**.sh"

jobs:
  shellcheck:
    name: lint-bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master
