name: smoke-test

on:
  push:
    branches:
      - main
    paths:
      - ".Brewfile"
      - ".tool-versions"
      - ".config/dotfiles/bootstrap.sh"
      - ".github/workflows/smoke.yml"
  pull_request:
    branches:
      - main
    paths:
      - ".Brewfile"
      - ".tool-versions"
      - ".config/dotfiles/bootstrap.sh"
      - ".github/workflows/smoke.yml"

jobs:
  bootstrap:
    name: Smoke test bootstrap script
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v3
      - name: Execute bootstrap script
        shell: bash
        run: bash .config/dotfiles/bootstrap.sh
