name: Smoke Test CI

on:
  push:
    paths:
      - ".config/dotfiles/bootstrap.sh"
      - ".Brewfile"
      - ".tool-versions"

jobs:
  bootstrap:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v3
      - name: Execute bootstrap script
        shell: bash
        run: bash .config/dotfiles/bootstrap.sh
