name: Smoke Test

on:
  push:
    paths:
      - ".Brewfile"
      - ".tool-versions"
      - ".config/dotfiles/bootstrap.sh"
      - ".github/workflows/smoke.yml"

jobs:
  bootstrap:
    runs-on: macOS-12

    steps:
      - uses: actions/checkout@v3
      - name: Execute bootstrap script
        shell: bash
        run: bash .config/dotfiles/bootstrap.sh
